owner: GrupoX-FIUBA # Your GitHub organization or username, where this repository lives
repo: services-status # The name of this repository

sites:
  - name: Music Service
    url: $MUSIC_SERVICE_URLdocs
    assignees:
      - ManuelBilbao
  - name: Users Service
    url: $URL_USERS_SERVICEdocs
    assignees:
      - RiedelNicolas
  - name: Feedback Service
    url: $FEEDBACK_SERVICE_URLdocs
    assigness:
      - ManuelBilbao
  - name: Payments Service
    url: $PAYMENTS_SERVICE_URLdocs
    assignees:
      - ezezbogar
  - name: API Gateway
    url: $API_GATEWAY_URLdocs
    assignees:
      - ezezbogar

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.spotifiuby.com.ar
  # baseUrl: /services-status
  logoUrl: https://spotifiuby.com.ar/assets/img/logos/logo_inverted.png
  name: Spotifiuby
  theme: night
  introTitle: "Status page for **Spotifiuby** microservices"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
